## Packages

[[packages]]
install = [ "dotdeploy-dev-r" ]
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"

[[packages]]
install = [
  "r",
  "opt:blas-openblas", "opt:gcc-fortran", "opt:texlive-latex"
]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"

[[packages]]
install = [ "R-devel" ]
if = "(eq DOD_DISTRIBUTION_NAME 'fedora')"


## Files

[[files]]
source = "Makevars"
target = "$HOME/.R/Makevars"
type = "copy"
template = true

[[files]]
source = "Rprofile"
target = "$HOME/.Rprofile"
