# Packages
[[packages]]
install = [ "dotdeploy/vm-virtualbox" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Deploy
[[tasks]]
description = "Add $USER to vboxusers"
[[tasks.config]]
shell = """
if ! id -nG "$USER" | grep -qw vboxusers; then
  sudo gpasswd -a "$USER" vboxusers
fi
"""
[[tasks.remove]]
shell = """
if id -nG "$USER" | grep -qw vboxusers; then
  sudo gpasswd -d "$USER" vboxusers
fi
"""
