# Packages
[[packages]]
install = [ "dotdeploy/vm-virtualbox" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Deploy
[[tasks]]
description = "virtualbox"
[[tasks.config]]
description = "Add $USER to vboxusers"
shell = '''
if ! id -nG "$USER" | grep -qw vboxusers; then
  sudo gpasswd -a "$USER" vboxusers
fi
'''
[[tasks.remove]]
description = "Remove $USER from vboxusers"
shell = '''
if id -nG "$USER" | grep -qw vboxusers; then
  sudo gpasswd -d "$USER" vboxusers
fi
'''
