# Packages
[[packages]]
install = [ "dotdeploy/vm-virtualbox" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Deploy
[[tasks]]
shell = """
sudo gpasswd -a "$USER" vboxusers
"""

[[tasks]]
shell = """
sudo gpasswd -d "$USER" vboxusers
"""
phase = "remove"
