## Packages

[[packages]]
install = [ "dotdeploy-shell-common" ]
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"

[[packages]]
install = [ "bat", "eza", "fd", "fzf", "tree", "tealdeer", "direnv" ]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"


## Includes

# TLDR
# [[includes]]
# files = [ "get_tldr.toml" ]

# Direnv
# [[includes]]
# files = [ "get_direnv.toml" ]
