## Tasks

# [[tasks]]
# description = "Rust setup"
# [[tasks.config]]
# description = "Install Cargo"
# shell = '''
# if [ ! -f "$HOME/.cargo/bin/cargo" ]; then
#   rustup-init -y --no-modify-path
# fi
# '''
# [[tasks.remove]]
# description = "Remove Cargo"
# shell = "rm -rf ~/.cargo"
