## Modules

depends_on = [
  "base",
  "shell/bash",
  "shell/zsh",
  "desktop/plasma",
  "desktop/apps/calibre",
  # "desktop/apps/libreoffice",
  "desktop/fonts",
  "desktop/spelling",
  "editors/emacs",
  "hardware/hp-printer",
  "dev/R",
  "dev/rust",
  "dev/containers",
  "services/samba",
  "vm/virtualbox",
  # "browsers/vivaldi",
  "backup/snapper"
]


## Config to include

[[includes]]
files = [
  "$DOD_HOSTS_ROOT/shared/env-sh.toml",
  "$DOD_HOSTS_ROOT/shared/fstrim.toml",
  "$DOD_HOSTS_ROOT/shared/hosts.toml",
  "$DOD_HOSTS_ROOT/shared/generators.toml"
]

[[includes]]
files = [ "$DOD_HOSTS_ROOT/shared/arch-system.toml" ]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"

[[includes]]
files = [ "tlp.toml" ]


## Packages

[[packages]]
install = [
  "nextcloud-client", "keepassxc",
  "input-remapper-git",
  # input-remapper optional
  "opt:xorg-xmodmap",
  "strawberry",
  # Bootloader management
  "limine-mkinitcpio-hook",
  "limine-snapper-sync",
  # Laptop power management
  "tlp", "tlp-rdw", "tlp-pd",
  "opt:ethtool", "opt:smartmontools"

]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"


## Files

# System tweaks
[[files]]
source = "tweaks/*"
target = "/etc/*"
type = "copy"

# Host specific dotfiles
[[files]]
source = "home/*"
target = "$HOME/*"

## Context variables for template expansion

[context_vars]
ncpu = "16"
