## TLP power management for laptops

[[tasks]]
description = "TLP"
[[tasks.config]]
description = "Activate TLP services"
shell = """
if ! systemctl is-enabled --quiet tlp.service tlp-pd.service; then
  sudo systemctl enable --now tlp.service tlp-pd.service
fi
sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket
"""
[[tasks.remove]]
description = "Deactivate TLP services"
shell = """
sudo systemctl disable --now tlp.service tlp-pd.service
sudo systemctl unmask systemd-rfkill.service systemd-rfkill.socket
"""
hook = "pre"
