## Packages

[[packages]]
install = [ "wslu" ]
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"


## Files

[[files]]
source = "wsl-binfmt.conf"
target = "/etc/binfmt.d/WSLInterop.conf"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"

[[files]]
source = "02-shared-root.sh"
target = "/etc/profile.d/02-shared-root.sh"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"


## Tasks

[[tasks]]
description = "Enable latest wslu PPA"
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"
[[tasks.setup]]
shell = "$DOD_DOTFILES_ROOT/scripts/ensure_ppa.sh wslutilities/wslu"
[[tasks.remove]]
shell = "sudo add-apt-repository --remove ppa:wslutilities/wslu"
