#!/usr/bin/env bash

# Set up environment

# Load any modifications of the environment early before we check if the shell
# is interactive or not.
[[ -f "$HOME/.env.sh" ]] && source "$HOME/.env.sh"
export PATH

IS_BASH="true"
IS_ZSH="false"

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# Prompt
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

if [ "$color_prompt" = yes ]; then
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='\u@\h:\w\$ '
fi
unset color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
    xterm*|rxvt*)
        PS1="\[\e]0;\u@\h: \w\a\]$PS1"
        ;;
    # Set prompt for Emacs TRAMP
    dumb)
        PS1="> "
        ;;
    *)
        ;;
esac

# Don't put duplicate lines or lines starting with space in the history. See
# bash(1) for more options
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# This requires https://forums.gentoo.org/viewtopic-t-1085654-start-0.html
# make less more friendly for non-text input files, see lesspipe(1)
# [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/bash lesspipe)"


#
## Custom settings

# Envvars
EDITOR=$(which nano)
export EDITOR

# fzf
[[ -f "$HOME/.fzf.sh" ]] && source "$HOME/.fzf.sh"

# Aliases
[[ -f "$HOME/.aliases.sh" ]] && source "$HOME/.aliases.sh"

unset IS_BASH
unset IS_ZSH
