## Packages
[[packages]]
install = [ "calibre", "opt:poppler", "python-fonttools" ]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"


## Files

[[files]]
source = "common/home/*"
target = "$HOME/*"
phase = "config"
type = "link"
