## Modules

depends_on = [
  "base",
  "shell/bash",
  "shell/zsh",
  "editors/emacs",
  "dev/R",
]

## Config to include

[[includes]]
files = [
  "$DOD_HOSTS_ROOT/shared/env-sh.toml",
  "$DOD_HOSTS_ROOT/shared/generators.toml"
]

## Context variables for template expansion

[context_vars]
ncpu = "14"
