## Config to include

# Ubuntu WSL config
[[includes]]
files = [ "ubuntu-wsl.toml" ]
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"

# Fedora container config
[[includes]]
files = [ "fedora-container.toml" ]
if = "(eq DOD_DISTRIBUTION_NAME 'fedora')"


[[includes]]
files = [
  "$DOD_HOSTS_ROOT/shared/env-sh.toml",
  "$DOD_HOSTS_ROOT/shared/generators.toml"
]

## Context variables for template expansion

[context_vars]
ncpu = "14"
