depends_on = [
  "base",
  "shell/bash",
  "desktop/spelling",
  "editors/emacs",
  "dev/R",
  "dev/python"
]


# Host specific dotfiles
[[files]]
source = "home/*"
target = "$HOME/*"

[[files]]
source = "distrobox-host-exec-wrapper.sh"
target = "$HOME/.local/bin/distrobox-host-exec"
