## Packages

[[packages]]
install = [
  "emacs-wayland",
  # Faster greping
  "ripgrep",
  # Faster projectile indexing
  "fd",
  # Copy to clipboard
  "xclip", "wl-clipboard",
  # Module dependencies
  # :lang latex & :emacs org
  "texlive", "texlive-lang",
  # :tools editorconfig
  "editorconfig-core-c",
  # :tools pdf-tools
  "poppler",
  # :checkers spell
  "enchant",
  # :tools lsp
  "npm"
]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"

[[packages]]
install = [
  "emacs-pgtk",
  "ripgrep",
  "fd-find",
  "xclip",
  "wl-clipboard",
  "texlive-scheme-medium",
  "editorconfig",
  # LSP server installs
  "nodejs"
]
if = "(eq DOD_DISTRIBUTION_NAME 'fedora')"


## Files

[[files]]
source = "common/home/*"
target = "$HOME/*"
phase = "config"


## Tasks

[[tasks]]
description = "Emacs"
[[tasks.config]]
description = "Install config"
exec = "$DOD_DOTFILES_ROOT/scripts/ensure_repo.sh"
args = [ "git@github.com:FrauH0lle/emacs.d.git", "~/.emacs.d" ]
hook = "pre"

[[messages]]
message = """
Remember to install the emacs configuration via 'emacs-config deploy'.
"""
