# Packages
[[packages]]
install = [ "dotdeploy/editors-emacs" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

[[packages]]
install = [ "dotdeploy-editors-emacs" ]
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"

# Files
# Package configuration
[[files]]
source = "gentoo/portage/*"
target = "/etc/portage/*"
phase = "setup"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

[[files]]
source = "common/home/*"
target = "$HOME/*"

# Actions
[[tasks]]
description = "Enable latest Emacs PPA"
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"
[[tasks.setup]]
exec = "$DOD_DOTFILES_ROOT/scripts/ensure_ppa.sh"
args = [ "ubuntuhandbook1/emacs" ]
[[tasks.remove]]
shell = "sudo add-apt-repository --remove ppa:ubuntuhandbook1/emacs"

[[tasks]]
description = "Emacs"
[[tasks.config]]
description = "Install config"
exec = "$DOD_DOTFILES_ROOT/scripts/ensure_repo.sh"
args = [ "git@github.com:FrauH0lle/emacs.d.git", "~/.emacs.d" ]

[[messages]]
message = """
Remember to install the emacs configuration via 'emacs-config deploy'.
"""
