# Modules
depends_on = [
  "base",
  "shell/bash",
  "shell/zsh",
  "desktop/plasma",
  "desktop/apps/calibre",
  "desktop/apps/libreoffice",
  "desktop/fonts",
  "desktop/spelling",
  "editors/emacs",
  "hardware/hp-printer",
  "dev/R",
  "dev/rust",
  "dev/containers",
  "services/samba",
  "vm/virtualbox",
  "browsers/vivaldi",
  "backup/snapper"
]

# Config to include
includes = [ "$DOD_HOSTS_ROOT/shared_configs/env-sh.toml" ]

# Packages
[[packages]]
install = [ "dotdeploy/host-yamato" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Files

# Host portage and package configuration
[[files]]
source = "gentoo/portage/*"
target = "/etc/portage/*"
phase = "setup"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# System tweaks
[[files]]
source = "gentoo/tweaks/*"
target = "/etc/*"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Host specific dotfiles
[[files]]
source = "home/*"
target = "$HOME/*"

# Files to generate
[[generators]]
source = "fzf.sh"
target = "$HOME/.fzf.sh"
shebang = "#!/bin/sh"

[[generators]]
source = "aliases.sh"
target = "$HOME/.aliases.sh"
shebang = "#!/bin/sh"

[[generators]]
source = "completions.sh"
target = "$HOME/.completions.sh"
shebang = "#!/bin/sh"

# Actions
[[tasks]]
description = "Enable fstrim service"
[[tasks.config]]
shell = "sudo systemctl enable fstrim.timer"

# Context variables for template expansion
[context_vars]
ncpu = "32"
