# Packages
[[packages]]
install = [ "dotdeploy/desktop-apps-libreoffice" ]
eval_when = "(eq DOD_DISTRO 'gentoo')"

# Files
[files]
# Package configuration
[files."/etc/portage/*"]
source = "gentoo/portage/*"
phase = "setup"
action = "copy"
eval_when = "(eq DOD_DISTRO 'gentoo')"
