# Packages
[[packages]]
install = [ "dotdeploy/desktop-apps-libreoffice" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Files
# Package configuration
[[files]]
source = "gentoo/portage/*"
target = "/etc/portage/*"
phase = "setup"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"
