# Packages
[[packages]]
install = [ "dotdeploy/hardware-hp-printer" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Files
# Package configuration
[[files]]
source = "gentoo/portage/*"
target = "/etc/portage/*"
phase = "setup"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Actions
[[tasks]]
description = "CUPS"
[[tasks.config]]
description = "Enable CUPS service"
shell = """
if ! systemctl is-enabled --quiet cups.socket; then
  sudo systemctl enable --now cups.socket
fi
"""
[[tasks.remove]]
description = "Disable CUPS service"
shell = """
sudo systemctl disable --now cups.socket
"""

[[tasks]]
[[tasks.config]]
description = "Add $USER to printer groups"
shell = '''
for GROUP in lp lpadmin scanner; do
  if ! id -nG "$USER" | grep -qw "$GROUP"; then
    sudo gpasswd -a "$USER" "$GROUP"
  fi
done
'''
[[tasks.remove]]
description = "Remove $USER from printer groups"
shell = '''
for GROUP in lp lpadmin scanner; do
  if id -nG "$USER" | grep -qw "$GROUP"; then
    sudo gpasswd -d "$USER" "$GROUP"
  fi
done
'''
