# Packages
[[packages]]
install = [ "dotdeploy/hardware-hp-printer" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Files
# Package configuration
[[files]]
source = "gentoo/portage/*"
target = "/etc/portage/*"
phase = "setup"
action = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Actions
[[tasks]]
shell = """
sudo systemctl enable --now cups.socket

sudo gpasswd -a "$USER" lp
sudo gpasswd -a "$USER" lpadmin
sudo gpasswd -a "$USER" scanner
"""
