## Packages

[[packages]]
install = [ "podman", "distrobox", "flatpak" ]
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"

[[packages]]
install = [
  "podman", "opt:podman-compose", "opt:podman-docker", "distrobox",
  "devcontainer-cli", "flatpak"
  ]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"


## Files

[[files]]
source = "distrobox/*"
target = "$HOME/distrobox/*"
phase = "config"


## Actions

[[tasks]]
description = "Enable latest Distrobox PPA"
if = "(eq DOD_DISTRIBUTION_NAME 'ubuntu')"
[[tasks.setup]]
shell = "$DOD_DOTFILES_ROOT/scripts/ensure_ppa.sh michel-slm/distrobox"
[[tasks.remove]]
shell = "sudo add-apt-repository --remove ppa:michel-slm/distrobox"

# Podman setup
[[tasks]]
description = "podman"
[[tasks.config]]
description = "Set subordinate UID/GIDs for $USER"
shell = "$DOD_DOTFILES_ROOT/scripts/subid_manager.sh setup"
[[tasks.config]]
description = "Enable podman socket"
shell = '''
if ! systemctl is-enabled podman.socket > /dev/null 2>&1; then
  systemctl --user enable --now podman.socket
fi
'''
hook = "post"
[[tasks.remove]]
description = "Remove subordinate UID/GIDs for $USER"
shell = "$DOD_DOTFILES_ROOT/scripts/subid_manager.sh remove"
hook = "post"
[[tasks.remove]]
description = "Disable podman socket"
shell = "systemctl --user disable --now podman.socket"
