# Packages
[[packages]]
install = [ "dotdeploy/desktop-plasma" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

[[packages]]
install = [
  # Meta packages/groups
  "kde-utilities",
  # ark optional
  "opt:7zip", "opt:arj", "opt:lrzip", "opt:lzop", "opt:unarchiver", "opt:unrar",
  "kde-system",
  "gwenview",
  "kdeconnect",
  "kdenetwork-filesharing",
  "okular",
  "opt:geoclue",
  # Evolution PIM
  "evolution", "evolution-ews", "gnome-keyring", "libgnome-keyring",
  # Themes
  "papirus-icon-theme",
  # Flatpak
  "xdg-desktop-portal-gtk",
  # Firefox
  "firefox",
  "jdownloader2",
  "octopi",
  "vlc", "vlc-plugins-all"
]
if = "(eq DOD_DISTRIBUTION_NAME 'arch')"

# # KDE tools
# RDEPEND="
# 	${RDEPEND}
# 	kde-misc/kdeconnect
# 	kde-misc/skanlite
# 	kde-apps/kdenetwork-filesharing
# 	kde-apps/gwenview
# 	kde-apps/okular
# "

# Files
# Package configuration
[[files]]
source = "gentoo/portage/*"
target = "/etc/portage/*"
phase = "setup"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

[[files]]
source = "49-wheel.rules"
target = "/etc/etc/polkit-1/rules.d/49-wheel.rules"
type = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Includes
[[includes]]
files = [ "pipewire.toml", "flathub.toml" ]
