# Packages
[[packages]]
install = [ "dotdeploy/browsers-vivaldi" ]
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"

# Files
[[files]]
source = "gentoo/portage/*"
target = "/etc/portage/*"
phase = "setup"
action = "copy"
if = "(eq DOD_DISTRIBUTION_NAME 'gentoo')"
