# Packages
[[packages]]
install = [ "dotdeploy/browsers-vivaldi" ]
eval_when = "(eq DOD_DISTRO 'gentoo')"

# Files
[files]
[files."/etc/portage/*"]
source = "gentoo/portage/*"
phase = "setup"
action = "copy"
eval_when = "(eq DOD_DISTRO 'gentoo')"
